[build]
  command = "npm --prefix frontend install --legacy-peer-deps && npm --prefix frontend run build"
  publish = "frontend/dist"

[build.environment]
  NODE_ENV = "development"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

