import jsPDF from "jspdf";
import type { ScheduleItem } from "../api/types";

const DAYS = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"];

// Colors matching the app theme
const COLORS = {
  primary: "#6366f1",
  secondary: "#f59e0b",
  text: "#0f172a",
  textMuted: "#64748b",
  border: "#e2e8f0",
  background: "#f8fafc",
};

export function generateSchedulePDF(items: ScheduleItem[], userName: string = "User") {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPos = margin;

  // === HEADER ===
  // QalamFlow title
  doc.setFontSize(24);
  doc.setTextColor(COLORS.primary);
  doc.text("QalamFlow", margin, yPos);

  yPos += 10;
  doc.setFontSize(12);
  doc.setTextColor(COLORS.textMuted);
  doc.text("Your Weekly Study Schedule", margin, yPos);

  // User name and date (right aligned)
  doc.setFontSize(10);
  doc.setTextColor(COLORS.text);
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`Generated for: ${userName}`, pageWidth - margin, margin, { align: "right" });
  doc.text(dateStr, pageWidth - margin, margin + 5, { align: "right" });

  yPos += 15;

  // === SEPARATOR LINE ===
  doc.setDrawColor(COLORS.border);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // === MOTIVATIONAL QUOTE ===
  doc.setFontSize(9);
  doc.setTextColor(COLORS.secondary);
  doc.setFont("helvetica", "italic");
  const quote = '"The ink of a scholar is more precious than the blood of a martyr."';
  doc.text(quote, pageWidth / 2, yPos, { align: "center" });
  doc.setFont("helvetica", "normal");
  yPos += 10;

  // === WEEKLY SCHEDULE TABLE ===
  doc.setFontSize(14);
  doc.setTextColor(COLORS.text);
  doc.setFont("helvetica", "bold");
  doc.text("Weekly Schedule", margin, yPos);
  doc.setFont("helvetica", "normal");
  yPos += 8;

  // Group items by day
  const byDay: Record<string, ScheduleItem[]> = {};
  DAYS.forEach((day) => {
    byDay[day] = items.filter((item) => item.dayOfWeek === day);
  });

  // Draw table
  const tableStartY = yPos;
  const colWidth = (pageWidth - 2 * margin) / 2;
  const rowHeight = 12;

  // Table header
  doc.setFillColor(COLORS.primary);
  doc.rect(margin, yPos, colWidth, rowHeight, "F");
  doc.rect(margin + colWidth, yPos, colWidth, rowHeight, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Day", margin + 3, yPos + 8);
  doc.text("Sessions", margin + colWidth + 3, yPos + 8);
  doc.setFont("helvetica", "normal");
  yPos += rowHeight;

  // Table rows
  doc.setTextColor(COLORS.text);
  doc.setFontSize(10);

  DAYS.forEach((day, index) => {
    const sessions = byDay[day];

    // Alternate row colors
    if (index % 2 === 0) {
      doc.setFillColor(COLORS.background);
      doc.rect(margin, yPos, pageWidth - 2 * margin, rowHeight, "F");
    }

    // Draw borders
    doc.setDrawColor(COLORS.border);
    doc.rect(margin, yPos, colWidth, rowHeight);
    doc.rect(margin + colWidth, yPos, colWidth, rowHeight);

    // Day name
    doc.setFont("helvetica", "bold");
    doc.text(day.charAt(0).toUpperCase() + day.slice(1), margin + 3, yPos + 8);
    doc.setFont("helvetica", "normal");

    // Sessions
    if (sessions.length === 0) {
      doc.setTextColor(COLORS.textMuted);
      doc.text("—", margin + colWidth + 3, yPos + 8);
      doc.setTextColor(COLORS.text);
    } else {
      let sessionY = yPos + 8;
      sessions.forEach((session, idx) => {
        const bookTitle = session.bookId && typeof session.bookId === "object"
          ? session.bookId.title
          : "";
        const sessionText = `${session.time} - ${session.activity}${bookTitle ? ` (${bookTitle})` : ""}`;

        // If text is too long, truncate
        const maxWidth = colWidth - 6;
        const lines = doc.splitTextToSize(sessionText, maxWidth);

        if (idx > 0) sessionY += 4; // Space between sessions
        doc.text(lines[0], margin + colWidth + 3, sessionY);

        if (lines.length > 1) {
          sessionY += 4;
          doc.setFontSize(8);
          doc.setTextColor(COLORS.textMuted);
          doc.text(lines.slice(1).join(" "), margin + colWidth + 3, sessionY);
          doc.setFontSize(10);
          doc.setTextColor(COLORS.text);
        }
      });
    }

    yPos += rowHeight;

    // Check if we need a new page
    if (yPos > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }
  });

  // === FOOTER ===
  const footerY = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(COLORS.textMuted);
  doc.text("Generated by QalamFlow - Your Islamic Learning Companion", pageWidth / 2, footerY, {
    align: "center",
  });

  // === DOWNLOAD ===
  const fileName = `QalamFlow_Schedule_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
}
